# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache: packages
latex: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

branches:
  only:
  - main


matrix:
  include:
    - r: 3.5
    - r: release
    - os: osx


addons:
  apt:
    packages:
      - libgit2-dev
