---
title: "a little test"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{a little test}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(idaifieldR)
```


```{r}
idaifield_docs <- get_idaifield_docs(serverip = "192.168.2.21",
                                     user = "Lisa Steinmann",
                                     pwd = "hallo",
                                     projectname = "testproj")

length(idaifield_docs)
```
okay.


```{r eval=FALSE}
#str(idaifield_docs)
```

```{r}
pottery <- select_by_type(idaifield_docs, type = "Pottery")

pottery <- convert_to_df(pottery)

head(pottery)
```


```{r}
uidlist <- get_uid_type_list(idaifield_docs, verbose = TRUE)

library(tidyverse)
uidlist

new <- left_join(pottery, uidlist[,c(1,2)], by = c("liesWithin" = "uid"))

```


Keramikfragmente pro Befund:

```{r}
ggplot(new, aes(x = identifier.y)) +
  geom_bar()
```


```{r}
ggplot(new, aes(x = identifier.y, fill = materialType)) +
  geom_bar()
```
