# source https://github.com/ropensci-archive/sofa/blob/master/.github/workflows/R-check.yaml
on:
  push:
    branches: [api]

name: CouchDB Test

jobs:
  R-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.rshort }}-couch(${{ matrix.config.couch }}))

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: ubuntu-16.04, r: 'release', rshort: 'rel', couch: 'latest'}

    services:
      couchdb:
        image: couchdb:${{ matrix.config.couch }}
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: password
        ports:
          - 5984:5984

    env:
      COUCHDB_TEST_USER: admin
      COUCHDB_TEST_PWD: password

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - uses: r-lib/actions/setup-tinytex@master
