on:
    push:
      branches: 
        couchdb-test
  
name: try to run couchdb
  
jobs:
  run-couchdb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up CouchDB
        uses: "lsteinmann/couchdb-action@master"
        with:
          couchdb version: '2.3.1'
      - name: See if running
        run: |
          curl http://127.0.0.1:5984/